services:
  - type: web
    name: hospital-chatbot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: LLM_PROVIDER
        value: typhoon
      - key: EMBEDDING_PROVIDER
        value: typhoon
      - key: TYPHOON_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000
